add_newline = true
continuation_prompt = "▶▶"

format = "$time$memory_usage$directory$git_branch$git_status$python$nodejs\n❯ "

[package]
disabled = true

[time]
disabled = false
style = "bold green"
format = '[$time]($style) '
time_format = "%H:%M"

[directory]
truncation_length = 80
truncate_to_repo = false
truncation_symbol = "/"
style = "bold cyan"
format = "[$path]($style) "

[git_branch]
symbol = ""
format = "[($symbol$branch )]($style)"
style = "bold yellow"


[git_status]
modified = "•${count}"
staged = "✔${count}"
untracked = "${count}Ɂ"
style = "yellow"
format = "[($modified )($staged )($untracked )]($style)"

[python]
style = "bright-yellow"
format = '[(python@${version} )]($style)'

[nodejs]
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
style = "bright-yellow"
format = '[(node@${version} )]($style)'

[memory_usage]
disabled = false
threshold = -1
format = "[used RAM: ${ram_pct}]($style) "
style = "bold blue"



















